SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE trigger;
TRUNCATE TABLE job;
SET REFERENTIAL_INTEGRITY TRUE;
ALTER TABLE trigger ALTER COLUMN id RESTART WITH 1;
ALTER TABLE job ALTER COLUMN id RESTART WITH 1;
INSERT INTO trigger(id, name, triggergroup, cron) VALUES(1, 'EveryFiveMinutesTrigger', 'EveryFiveMinutesTrigger', '0 0/5 * 1/1 * ? *');
INSERT INTO trigger(id, name, triggergroup, cron) VALUES(2, 'HourlyTrigger', 'HourlyTrigger', '* * 0/1 ? * * *');
INSERT INTO trigger(id, name, triggergroup, cron) VALUES(3, 'HalfHourlyTrigger', 'HalfHourlyTrigger', '0 0/30 * 1/1 * ? *');
INSERT INTO trigger(id, name, triggergroup, cron) VALUES(4, 'EveryTwoMinutesTrigger', 'EveryTwoMinutesTrigger',  '0 0/2 * 1/1 * ? *');
INSERT INTO trigger(id, name, triggergroup, cron) VALUES(5, 'EveryMinuteTrigger', 'EveryMinuteTrigger', '* 0/1 0 ? * * *');
INSERT INTO trigger(id, name, triggergroup, cron) VALUES(6, 'EverySUN12PM', 'WeeklyTriggerSun', '0 0 12 ? * SUN');
INSERT INTO job(id, jobname, trigger_id, jobgroup, status) VALUES (1, 'SendEmailJob', 4, 'Email-Job-Group', 'QUEUED' );
INSERT INTO job(id, jobname, trigger_id, jobgroup, status) VALUES (2, 'LoadUpstreamDataJob', 2, 'Data-Load-Group', 'QUEUED' );
INSERT INTO job(id, jobname, trigger_id, jobgroup, status) VALUES (3, 'SendDownstreamFileJob', 3, 'Data-Load-Group', 'QUEUED' );
INSERT INTO job(id, jobname, trigger_id, jobgroup, status) VALUES (4, 'SendPushMessagesJob', 4, 'Marketing-Group', 'QUEUED' );
INSERT INTO job(id, jobname, trigger_id, jobgroup, status) VALUES (5, 'SendOfferJobs', 5, 'Marketing-Group', 'QUEUED' );
INSERT INTO job(id, jobname, trigger_id, jobgroup, status) VALUES (6, 'GetTokenJob', 1, 'Security-Group', 'QUEUED' );
INSERT INTO job(id, jobname, trigger_id, jobgroup, status) VALUES (7, 'RefreshCacheJob', 1, 'Cache-Group', 'QUEUED' );
INSERT INTO job(id, jobname, trigger_id, jobgroup, status) VALUES (8, 'LoadCacheJob', 3, 'Cache-Group', 'QUEUED' );
INSERT INTO job(id, jobname, trigger_id, jobgroup, status) VALUES (9, 'LogCleanUpJob', 4, 'Cache-Group', 'QUEUED' );
INSERT INTO job(id, jobname, trigger_id, jobgroup, status) VALUES (10, 'CheckDependentSystemsSatusJob', 5, 'System-Check-Group', 'QUEUED' );